# Generated by Django 5.1.4 on 2025-01-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_customuser_guardian_email_customuser_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('senior_admin', 'Senior Admin')], max_length=20),
        ),
    ]
